title: Gerardo J. Pérez Medina
logo: "images/bild.png"
description: |
  Data analyst with a solid background in molecular biology and over 5 years of experience
  in customer relationships within the Life Science field.
  Experienced with competencies in the analysis of small to large scale datasets, using Excel,
  SQL, Tableau, and Python.
show_downloads: False
theme: jekyll-theme-minimal
