title: Gerardo J. Pérez Medina
logo: "images/bild1.png"
description: |
  Certified data analyst with a passion for transforming datasets into actionable insights!
  I combine my background in marine biology and life science to boost creatively the ways i discover and present data-driven insights
  Dive into some of my projects, and get in touch if you have any questions! 
show_downloads: False
theme: jekyll-theme-minimal
