title: Gerardo J. Pérez Medina
logo: "images/bild1.png"
description: |
  I am a data analyst with a passion for transforming datasets into actionable insights!
show_downloads: False
theme: jekyll-theme-minimal 

