title: Gerardo J. Pérez Medina
logo: "images/bild1.png"
description: |
  I am a certified data analyst with a passion for transforming datasets into actionable insights!
  email - geramed.perez@gmail.com
linkedin: "https://www.linkedin.com/in/gerardo-perez-medina/"
show_downloads: False
theme: jekyll-theme-minimal
